name: Android CI

on:
  push:
    branches: [ "exercise0" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      build:
      name: Java ${{ matrix.java }} Maven Test on ${{ matrix.os }}
      strategy:
        matrix:
          # Test against the LTS Java versions. TODO: add JDK18 when it becomes available.
          java: [ 8.0.x, 11.0.x, 17.0.x ]
          os: [ macos-latest, windows-latest, ubuntu-latest ]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}
        - name: Cache local Maven repository
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('pom.xml', '**/pom.xml') }}
        - name: Build with Maven
          shell: bash
          run: |
            if [ $(grep -E '^(8|11)\.' <<< '${{ matrix.java }}') ]; then
              # some module doesn't compile on java platform lower than 17, need to skip them by specifying a profile
              MODS_OVERRIDES='-pl !spring-aot'
            fi
            mvn -q -B --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn $MODS_OVERRIDES clean test

