name: Android CI

on:
  push:
    branches: [ "exercise0" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Gradle
        uses: maven/maven-build-action@v2
      - name: Build app
        run: ./mvn compile
