name: Android CI

on:
  push:
    branches: [ "exercise0" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('pom.xml', '**/pom.xml') }}
      - name: Build with Maven
        shell: bash
        run: |
          if [ $(grep -E '^(8|11)\.' <<< '${{ matrix.java }}') ]; then
            # some module doesn't compile on java platform lower than 17, need to skip them by specifying a profile
            MODS_OVERRIDES='-pl !spring-aot'
          fi
          mvn -q -B --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn $MODS_OVERRIDES clean test

