name: Tests

on:
  push:
    branches:
    - '*'

jobs:
  build:
    name: Java ${{ matrix.java }} Maven Test on ${{ matrix.os }} 
    strategy:
      matrix:
        # Test against the LTS Java versions. TODO: add JDK18 when it becomes available.
        java: [17.0.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('pom.xml', '**/pom.xml') }}
      - name: Build with Maven
        shell: bash
        run: |
            for d in */ ; do
              cd "$d"
              mvn test
              cd ..
            done

